name: parallel Process workflow
on: [push, workflow_dispatch]
jobs:
  Preparing-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: init-gradle
        run: gradle init
      - name: build with gradle
        run: gradle  build -x test
      - name: Cache Gradle output
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  Running-test-job :
    runs-on: ubuntu-latest
    needs: Preparing-system
    strategy:
        matrix:
          package: ['*service*', '*controller*', '*mapper*', '*repository*']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore Gradle output from cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
      - name: run tests
        run: gradle test --rerun-tasks --tests  ${{ matrix.package }}






